### ISSUE TITLE
Javascript RangeError on appointment change causing disabled calendar dates

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [alextselegidis/easyappointments#1092]
Hi there,

when customers change an appointment via email-link, there is an JS-error in the console: Uncaught RangeError: 31 is not a valid value for day.

This only happens if the appointment month is NOT current month! Then the appointment date is marked, but the calendar shows only disabled dates including the marked one. If you then switch the month in the calendar, everything works fine again.

I attached some screenshots. Appointment date was 1. Juli 2021. With Juni dates everything was okay (no JS error).

![ea_js_error](https://user-images.githubusercontent.com/51790093/122538530-f1438200-d026-11eb-99c3-be0f9da843a3.png)
![ea_fe_calendar_on_init_-_wrong](https://user-images.githubusercontent.com/51790093/122538557-f7396300-d026-11eb-87da-9b40a3c88669.png)
![ea_fe_calendar_after_switching_month_-_right](https://user-images.githubusercontent.com/51790093/122538572-faccea00-d026-11eb-87f1-90ae8bc500e8.png)

**Comment by alextselegidis** [comment]
Hello! 

Thanks, let me check this and get back to you. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Fixed on develop

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Hi,

the browser console error is still in 1.4.2 as described in my initial comment (customer edits his appointment). Appointment is in next month (october) and september has no valid dates.
